#add this to your repositorys cd workflow
jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: make folder for reports
        run: mkdir reports

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@main
        with:
          test_env: #localhost, test or dev
          browser: #chromium, firefox, webkit
          test_tag: #if you want to add specific tagg for which tests to run
          front_end_version: #which docker image to use
          back_end_version: #which docker image to use

      - name: docker copy
        if: always()
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
