name: "E2E tests"
description: "Builds test environment and runs e2e tests"
inputs:
  test_suite_version:
    description: Which version of tests to use (docker image tag)
    required: false
    default: "latest"
  test_env:
    description: test environment name to select correct robot framework env variables
    required: false
    default: "localhost"
  browser:
    description: browser for running tests
    required: false
    default: "chromium"
  included_tag:
    description: Tag for which tests to run
    required: false
    default: "smoke"
  e2e_username:
    description: Email address for robot user
    required: true
  e2e_password:
    description: Password for robot user
    required: true

runs:
  using: "composite"
  steps:
    - name: Create folder for reports
      run: mkdir -p ${{ github.workspace }}/reports
      shell: bash

    - name: Run Robot tests in started environment
      run: |
        docker run --name "robot-tests" \
          --network="host" \
            hsldevcom/jore4-robot:${{ inputs.test_suite_version }}\
              bash -c "robot -v ENV:${{ inputs.test_env }} -v BROWSER:${{ inputs.browser }} -v PASSWORD:${{ inputs.e2e_password }} -v EMAIL:${{ inputs.e2e_username }} --include ${{ inputs.included_tag }} --outputdir /tests/output /tests"
      shell: bash
