name: "E2E tests"
description: "Builds test environment and runs e2e tests"
inputs:
  frontend_version:
    description: version of ui to use
    required: false
    default: "latest"
  backend_version:
    description: version of backend to use
    required: false
    default: "latest"
  test_env:
    description: test environment name to select correct robot framework env variables
    required: false
    default: "localhost"
  browser:
    description: browser for running tests
    required: false
    default: "chromium"
  included_tag:
    description: Tag for which tests to run
    required: false
    default: "smoke"

runs:
  using: "composite"
  steps:
    - name: Setup e2e cluster with the remote script
      #add BACKEND_DOCKER_IMAGE=hsldevcom/jore4-backend:${{ inputs.backend_version}} to the run command when there are images for it
      run: "curl FRONTEND_DOCKER_IMAGE=hsldevcom/jore4-ui:${{ inputs.frontend_version }} https://raw.githubusercontent.com/HSLdevcom/jore4-flux/e2e/remotecluster.sh | bash"
      shell: bash

    - name: Verify that application is up and running
      run: |
        for i in {1..20}; do
          curl --fail http://localhost:8000 --output /dev/null --silent && break
          sleep 5
          echo $i
        done
      shell: bash

    - name: Run Robot tests in started environment
      run: |
        docker run --name "robot-tests"\
          --network="host" \
            hsldevcom/jore4-robot:latest \
              bash -c "robot -v ENV:${{ inputs.test_env }} -v BROWSER:${{ inputs.browser }} --include ${{ inputs.included_tag }} --nostatusrc --outputdir /tests/output /tests"
      shell: bash
