name: CI
on:
  push:
    branches:
      - main
      - actions
  pull_request:

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build & Push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t jore4-robot .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JORE4_DOCKERHUB_USER }}
          password: ${{ secrets.JORE4_DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: docker push jore4-robot
