name: Run tests on push to main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: make folder for reports
        run: mkdir reports

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@v1
        with:
          test_env: test

      - name: Retrieve test results from docker container
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Expose test results as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ${{ github.workspace }}/reports
