# runs tests for push-events, for pull requests and using cron schedule:
name: Test Env Robot Run
on:
  push:
    branches:
      - main
      - report
    # do not run tests if file README.md changes
    paths-ignore:
      - 'README.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - name: make folder for reports
          run: mkdir reports
        - name: Run Robot Framework Tests Manually
          run: |
            docker run --name "robot-tests"\
              hsldevcom/jore4-robot:latest \
                bash -c "robot -v ENV:test -v BROWSER:chromium --outputdir /tests/output /tests"
        - name: docker copy
          run: docker cp robot-tests:/tests/output ${{ github.workspace }}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

    generate_report:
        if: always()
        needs: [run_tests]
        runs-on: ubuntu-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Get Repository Owner & Name
          run: |
            echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
            echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          env:
            GH_ACCESS_TOKEN: ${{ github.TOKEN }}
            REPO_OWNER: $REPOSITORY_OWNER
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: $REPOSITORY_NAME
            REPORT_PATH: reports
