name: Run Robot Framework tests for test environment
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: make folder for reports
        run: mkdir reports

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@main
        with:
          test_env: test

      - name: docker copy
        if: always()
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
