name: Run tests after new commit
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Extract repository metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Build docker image for distribution
        run: docker build -t $IMAGE_NAME:ci .

      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
        with:
          ui_version: hsldevcom/jore4-ui:latest
          hasura_version: hsldevcom/jore4-hasura:seed-fix-seed-data--326c76930b66fb12faa2913d7d738ed8fc61cfaa

      - name: run e2e smoke tests
        uses: ./github-actions/run-rf-tests
        with:
          test_suite_version: ci
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: upload test results
        if: always()
        uses: ./github-actions/upload-results

      - name: Check that reports folder contains log.html
        run: |
          FILE=${{ github.workspace }}/reports/log.html
          if [ -f "$FILE" ]; then
            echo "File $FILE exists"
          else
            echo "File $FILE does not exist"
            exit 1
          fi
