name: Testing rf-tests action

on:
  push:

jobs:
  test_e2e_action:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract repository metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1

      - name: run simple health check test
        id: tests
        uses: ./github-actions/run-rf-tests
        with:
          included_tag: action_health_check

      - name: Retrieve test results from docker container
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Check that reports folder contains log.html
        run: |
          FILE=${{ github.workspace }}/reports/log.html
          if [ -f "$FILE" ]; then
            echo "File $FILE exists"
          else
            echo "File $FILE does not exist"
            exit 1
          fi
