name: Testing e2e action

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  create_tag_for_testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Tag commit as testing
        #used to specify the version of the action used in the next jobs
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/testing",
              sha: context.sha
            })

  test_e2e_action:
    needs: create_tag_for_testing
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          # no overwrites
          - ui-docker-image: ""
            hasura-docker-image: ""
          # overwrite all
          - ui-docker-image: "hsldevcom/jore4-ui:latest"
            hasura-docker-image: "hsldevcom/jore4-hasura:latest"
          # overwrite some
          - ui-docker-image: "hsldevcom/jore4-ui:latest"
            hasura-docker-image: ""

    steps:
      # note that we don't checkout code in this job to make sure that the script works from an empty workspace!
      - name: Verifying that current workspace is empty
        run: '[ -z "$(ls -A)" ]'

      - name: Extract repository metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: make folder for reports
        run: mkdir reports

      - name: run simple health check test
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@testing
        with:
          ui_version: ${{ matrix.ui-docker-image }}
          hasura_version: ${{ matrix.hasura-docker-image }}
          test_suite_version: ${{ env.COMMIT_ID }}
          included_tag: action_health_check

      - name: docker copy
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Check that reports folder contains log.html
        run: |
          FILE=${{ github.workspace }}/reports/log.html
          if [ -f "$FILE" ]; then
            echo "File $FILE exists"
          else
            echo "File $FILE does not exist"
            exit 1
          fi

      - name: Verify that UI is up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          # Kind cluster takes long time to start
          retries: 50
          command: "curl --fail http://localhost:3300 --output /dev/null --silent"

      - name: Verify that hasura is up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: "curl --fail http://localhost:3300/graphql/healthz --output /dev/null --silent"

      - name: Testing that the correct version got deployed from ui
        # if matrix.ui-docker-image is defined should use that, otherwise use default
        run: |
          UI_DEPLOYED_VERSION=`kubectl get deployment jore4-ui --namespace hsl-jore4 --output jsonpath='{.spec.template.spec.containers[0].image}'`
          if [[ "${{ matrix.ui-docker-image }}" == "" ]]
          then
            [[ "$UI_DEPLOYED_VERSION" != "${{ matrix.ui-docker-image }}" ]]
          else
            [[ "$UI_DEPLOYED_VERSION" == "${{ matrix.ui-docker-image }}" ]]
          fi

      - name: Testing that the correct version got deployed from hasura
        # if matrix.hasura-docker-image is defined should use that, otherwise use default
        run: |
          HASURA_DEPLOYED_VERSION=$(kubectl get deployment jore4-hasura --namespace hsl-jore4 --output jsonpath='{.spec.template.spec.containers[0].image}')
          if [[ "${{ matrix.hasura-docker-image }}" == "" ]]
          then
            [[ "$HASURA_DEPLOYED_VERSION" != "${{ matrix.hasura-docker-image }}" ]]
          else
            [[ "$HASURA_DEPLOYED_VERSION" == "${{ matrix.hasura-docker-image }}" ]]
          fi

      - name: Stop Kind
        run: "curl https://raw.githubusercontent.com/HSLdevcom/jore4-flux/e2e/kindcluster.sh | bash -s -- stop"

  delete_tag_after_testing:
    needs: test_e2e_action
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Remove tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/testing"
            })
