name: Test action for e2e testing

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  create_tag_for_testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Tag commit as testing
        #used to specify the version of the action used in the next jobs
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/testing",
              sha: context.sha
            })

  test_e2e_action:
    needs: create_tag_for_testing
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          # no overwrites
          - frontend-docker-image: ""
            backend-docker-image: ""
          # overwrite all
          - frontend-docker-image: "hsldevcom/jore4-ui:latest"
            backend-docker-image: "hsldevcom/jore4-backend:latest"
          # overwrite some
          - frontend-docker-image: "hsldevcom/jore4-ui:latest"
            backend-docker-image: ""

    steps:
      # note that we don't checkout code in this job to make sure that the script works from an empty workspace!
      - name: Verifying that current workspace is empty
        run: '[ -z "$(ls -A)" ]'

      - name: make folder for reports
        run: mkdir reports

      - name: run simple health check test
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@testing
        with:
          frontend_version: ${{ matrix.frontend-docker-image }}
          backend_version: ${{ matrix.backend-docker-image }}
          included_tag: action_health_check

      - name: docker copy
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Check that reports folder contains log.html
        run: |
          FILE=${{ github.workspace }}/reports/log.html
          if [ -f "$FILE" ]; then
            echo "File $FILE exists"
          else
            echo "File $FILE does not exist"
            exit 1
          fi

      - name: Testing that the correct version got deployed from frontend
        # if matrix.frontend-docker-image is defined should use that, otherwise use default
        run: |
          FRONTEND_DEPLOYED_VERSION=`kubectl get deployment jore4-frontend --namespace hsl-jore4 --output jsonpath='{.spec.template.spec.containers[0].image}'`
          if [[ "${{ matrix.frontend-docker-image }}" == "" ]]
          then
            [[ "$FRONTEND_DEPLOYED_VERSION" != "${{ matrix.frontend-docker-image }}" ]]
          else
            [[ "$FRONTEND_DEPLOYED_VERSION" == "${{ matrix.frontend-docker-image }}" ]]
          fi

      - name: Testing that the correct version got deployed from backend
        # if matrix.backend-docker-image is defined should use that, otherwise use default
        run: |
          BACKEND_DEPLOYED_VERSION=`kubectl get deployment jore4-backend --namespace hsl-jore4 --output jsonpath='{.spec.template.spec.containers[0].image}'`
          if [[ "${{ matrix.backend-docker-image }}" == "" ]]
          then
            [[ "$BACKEND_DEPLOYED_VERSION" != "${{ matrix.backend-docker-image }}" ]]
          else
            [[ "$BACKEND_DEPLOYED_VERSION" == "${{ matrix.backend-docker-image }}" ]]
          fi

      - name: Stop Kind
        run: "curl https://raw.githubusercontent.com/HSLdevcom/jore4-flux/e2e/kindcluster.sh | bash -s -- stop"

  delete_tag_after_testing:
    needs: test_e2e_action
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Remove tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/testing"
            })
