name: Manually triggered tests
on:
  workflow_dispatch:
    inputs:
      env:
        description: "In which env you want to run the tests in"
        default: localhost
        required: true
      browser:
        description: "Which browser you want to use"
        default: chromium
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: smoke
        required: true
jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: make folder for reports
        run: mkdir reports

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@v1
        with:
          test_env: ${{ github.event.inputs.env }}
          browser: ${{ github.event.inputs.browser }}
          included_tag: ${{ github.event.inputs.tag }}

      - name: Retrieve test results from docker container
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Expose test results as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ${{ github.workspace }}/reports
