name: Manually triggered tests
on:
  workflow_dispatch:
    inputs:
      env:
        description: "In which env you want to run the tests in"
        default: localhost
        required: true
      browser:
        description: "Which browser you want to use"
        default: chromium
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: smoke
        required: true
      version:
        description: "Which docker image you want to use"
        default: latest

jobs:
  run_e2e_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/.github/action@separate-env-setup
        with:
          test_env: ${{ github.event.inputs.env }}
          browser: ${{ github.event.inputs.browser }}
          included_tag: ${{ github.event.inputs.tag }}
          test_suite_version: ${{ github.event.inputs.version }}
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: Retrieve test results from docker container
        if: always()
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Expose test results as an artifact
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: ${{ github.workspace }}/reports
