# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests Manually
on:
  workflow_dispatch:

    inputs:
      env:
        description: 'In which env you want to run the tests in'
        default: test
        required: true
      browser:
        description: 'Which browser you want to use'
        default: chromium
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        # Default value if no value is explicitly provided
        default: smoke
        # Input has to be provided for the workflow to run
        required: true
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Robot Framework Tests Manually
          run: |
            docker run --rm \
              --user pwuser:pwuser \
                --volume ${PWD}/tests:/tests:Z \
                    hsldevcom/jore4-robot:latest \
                      bash -c "robot -v ENV:${{ github.event.inputs.env }} -v BROWSER:${{ github.event.inputs.browser }} --include ${{ github.event.inputs.tag }} --outputdir /tests/output /tests"
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/tests/output

    generate_report:
        if: always()
        needs: [run_tests]
        runs-on: ubuntu-latest
        steps:
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Get Repository Owner & Name
          run: |
            export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
            export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
            echo "::set-env name=REPOSITORY_OWNER::$OWNER"
            echo "::set-env name=REPOSITORY_NAME::$REPO"
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          env:
            GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
            REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
            COMMIT_SHA: ${{ github.sha }}
            REPOSITORY: ${{ env.REPOSITORY_NAME }}
            REPORT_PATH: reports
