name: Run Robot Framework Tests Manually
on:
  workflow_dispatch:
    inputs:
      env:
        description: "In which env you want to run the tests in"
        default: test
        required: true
      browser:
        description: "Which browser you want to use"
        default: chromium
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: smoke
        required: true
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: make folder for reports
        run: mkdir reports

      - name: run e2e smoke tests
        id: test-results
        uses: HSLdevcom/jore4-robot/.github/action@robot_action
        with:
          test_env: ${{ github.event.inputs.env }}
          browser: ${{ github.event.inputs.browser }}
          test_tag: ${{ github.event.inputs.tag }}

      - name: echo log.html
        if: always()
        run: echo "the file is this ${{ steps.test-results.outputs.results }}"

      - name: docker copy
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
