# runs tests for push-events, for pull requests and using cron schedule:
name: Run Robot Framework Tests Manually
on:
  workflow_dispatch:
    inputs:
      env:
        description: "In which env you want to run the tests in"
        default: test
        required: true
      browser:
        description: "Which browser you want to use"
        default: chromium
        required: true
      tag:
        description: 'Tag for tests to run. Use "*" to run all'
        default: smoke
        required: true
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: new action
        uses: HSLdevcom/jore4-robot/.github/action@robot_action
      - name: make folder for reports
        run: mkdir reports
      - name: Run Robot Framework Tests Manually
        run: |
          docker run --name "robot-tests"\
            hsldevcom/jore4-robot:latest \
              bash -c "robot -v ENV:${{ github.event.inputs.env }} -v BROWSER:${{ github.event.inputs.browser }} --include ${{ github.event.inputs.tag }} --outputdir /tests/output /tests"
      - name: docker copy
        run: docker cp robot-tests:/tests/output/. ${{ github.workspace }}/reports/
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
